export const chatPrompts: string[] = [
  "How are you feeling right now?",
  "What was the best part of your day?",
  "Is there something bothering you today?",
  "Did anything make you smile today?",
  "Want to tell me about something you're proud of?",
  "Was today a good day or a tricky one?",
  "If your feelings were weather, what kind of day would it be?",
  "What color do you feel like today? Why?",
  "If your mood was a sound, what would it sound like?",
  "What made you feel calm or safe today?",
  "What's something you're getting better at?",
  "Tell me about a time you were really brave.",
  "What's something you've learned recently that surprised you?",
  "If you could change one thing about today, what would it be?",
  "What's one small thing that made you feel happy?",
  "If you had a magic button that paused the world, what would you do?",
  "What would your perfect day look like?",
  "What's something you wish people understood about you?",
  "If you could talk to your future self, what would you ask?",
  "If today was a movie, what would the title be?"
];

export const promptStarters = [
  { prompt: "How are you feeling right now?", starter: "Right now I'm feeling… " },
  { prompt: "What was the best part of your day?", starter: "The best part of my day was… " },
  { prompt: "Is there something bothering you today?", starter: "Something that's been bothering me is… " },
  { prompt: "Did anything make you smile today?", starter: "Something that made me smile today was… " },
  { prompt: "Want to tell me about something you're proud of?", starter: "Something I'm really proud of is… " },
  { prompt: "Was today a good day or a tricky one?", starter: "Today was… " },
  { prompt: "If your feelings were weather, what kind of day would it be?", starter: "If my feelings were weather, it would be… " },
  { prompt: "What color do you feel like today? Why?", starter: "Today I feel like the color… " },
  { prompt: "If your mood was a sound, what would it sound like?", starter: "If my mood was a sound, it would sound like… " },
  { prompt: "What made you feel calm or safe today?", starter: "Something that made me feel calm today was… " },
  { prompt: "What's something you're getting better at?", starter: "Something I'm getting better at is… " },
  { prompt: "Tell me about a time you were really brave.", starter: "A time I was really brave was when… " },
  { prompt: "What's something you've learned recently that surprised you?", starter: "Something I learned that surprised me was… " },
  { prompt: "If you could change one thing about today, what would it be?", starter: "If I could change one thing about today, it would be… " },
  { prompt: "What's one small thing that made you feel happy?", starter: "A small thing that made me happy was… " },
  { prompt: "If you had a magic button that paused the world, what would you do?", starter: "If I could pause the world, I would… " },
  { prompt: "What would your perfect day look like?", starter: "My perfect day would be… " },
  { prompt: "What's something you wish people understood about you?", starter: "Something I wish people understood about me is… " },
  { prompt: "If you could talk to your future self, what would you ask?", starter: "If I could talk to my future self, I would ask… " },
  { prompt: "If today was a movie, what would the title be?", starter: "If today was a movie, it would be called… " }
];