export const whatIfPrompts: string[] = [
  "What if your robot buddy had a secret power—what would it be?",
  "What if you could fly anywhere in the world right now—where would you go?",
  "What if animals could talk—which animal would be your best friend?",
  "What if you could be invisible for one day—what would you do?",
  "What if you found a magic door in your room—where would it lead?",
  "What if you could time travel—would you go to the past or future?",
  "What if you could breathe underwater—what would you explore?",
  "What if you could shrink down to the size of an ant—what adventure would you have?",
  "What if you could speak any language instantly—which would you choose?",
  "What if you could control the weather—what kind of day would you make?",
  "What if you could talk to plants—what would they tell you?",
  "What if you could live in any book—which story would you choose?",
  "What if you could have any superpower for a week—what would it be?",
  "What if you could build the perfect treehouse—what would be inside?",
  "What if you could eat clouds—what do you think they'd taste like?",
  "What if you could paint with colors that don't exist—what would you create?",
  "What if you could have a conversation with your future self—what would you ask?",
  "What if you could make one rule that everyone had to follow—what would it be?",
  "What if you could turn into any animal for a day—which would you pick?",
  "What if you could live on any planet—what would your new home be like?",
  "What if you could make anything you drew come to life—what would you draw first?",
  "What if you could have dinner with any person from history—who would it be?",
  "What if you could create a new holiday—what would people celebrate?",
  "What if you could make gravity work backwards for an hour—what would you do?",
  "What if you could understand what your pet is thinking—what do you think they'd say?",
  "What if you could live in a world made entirely of your favorite food—what would it be?",
  "What if you could have a robot that did one thing perfectly—what would you want it to do?",
  "What if you could make one thing in the world bigger or smaller—what would you change?",
  "What if you could create a new color—what would you name it and where would you use it?",
  "What if you could have a magical backpack that never ran out of space—what would you keep in it?"
];